name: Running tests

on:
  push:
    branches: [ main ]

jobs:
    newman:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: matt-ball/newman-action@master
        with:
            collection: collections/QAAutomation.postman_collection.json